# Generated by Django 4.2.24 on 2025-11-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(blank=True, max_length=50)),
                ('chapter', models.CharField(blank=True, max_length=100)),
                ('article_no', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('simple_text_en', models.TextField()),
                ('simple_text_hi', models.TextField(blank=True, null=True)),
                ('original_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['article_no'],
            },
        ),
    ]
