# Generated by Django 4.2.24 on 2025-11-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_no', models.CharField(max_length=50)),
                ('offence_type', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bailable', models.BooleanField(default=False)),
            ],
        ),
    ]
